spring:
  application:
    name: oauth2-service

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      #配置中心地址
#      defaultZone: http://localhost:8081/eureka

  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456
server:
  port: 3000