eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #配置中心地址
      defaultZone: http://localhost:8081/eureka


server:
  port: 8888
spring:
  application:
    name: ssm-server
  datasource:
    url: jdbc:mysql://localhost:3306/myproject?setUnicode=true&characterEncoding=utf8
    username: root
    password: zw123
  kafka:
    bootstrap-servers: localhost:9092  #地址，多个中间使用,分割:127.0.0.1:9092,127.0.0.1:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer        #发送key类型
      value-serializer: org.apache.kafka.common.serialization.StringSerializer        #发送value类型
    consumer:
      group-id: TEST #群组ID
      enable-auto-commit: false        #停止（取消）自动发送
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer        #接收key类型
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer        #接收value类型