jasypt:
  encryptor:
    # 指定加解密在spring ioc容器中bean的名称，默认 jasyptStringEncryptor
    bean: myStringEncryptor
    # 盐值
    password: bamboo
    property:
      # 标识为加密属性的前缀
      prefix: ENC(
      # 标识为加密属性的后缀
      suffix: )

# 滑块验证码
aj:
  captcha:
    # 缓存类型
    cache-type: redis
    # blockPuzzle 滑块 clickWord 文字点选  default默认两者都实例化
    type: blockPuzzle
    # 右下角显示字
    water-mark: ruoyi.vip
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 2

custom:
  expiration:
    time:
      bamboomusic_query: 300
  prefix:
    live_url: http://localhost:8888/bamboo.html?liveShareUrl=
