server:
  port: 8082

#指定服务器名称
spring:
  application:
    name: getway-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #配置中心地址
      defaultZone: http://localhost:8081/eureka